# Generated by Django 5.1.7 on 2026-03-21 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icono', models.CharField(default='bi-grid', help_text='Clase de Bootstrap Icons. Ej: bi-people', max_length=60)),
                ('url_name', models.CharField(blank=True, help_text='Nombre de la URL en urls.py. Ej: lista_usuarios', max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('accion', 'Acción'), ('componente', 'Componente'), ('dato', 'Dato')], max_length=20)),
                ('label', models.CharField(max_length=150)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='client.modulo')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'ordering': ['tipo', 'orden', 'clave'],
                'unique_together': {('modulo', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.SlugField(max_length=100)),
                ('tipo', models.CharField(choices=[('seccion', 'Sección completa'), ('campo', 'Campo del formulario'), ('boton', 'Botón de acción'), ('columna', 'Columna de tabla')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='client.modulo')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('modulo', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('modulo', 'Acceso a módulo'), ('elemento', 'Interacción con elemento')], max_length=20)),
                ('elemento_clave', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='client.modulo')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', '-fecha'], name='client_acti_usuario_f9519e_idx'), models.Index(fields=['tipo_evento', '-fecha'], name='client_acti_tipo_ev_f61a6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccesoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_acceso', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_modulos', to='auth.group')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='client.modulo')),
            ],
            options={
                'verbose_name': 'Acceso a Módulo',
                'verbose_name_plural': 'Accesos a Módulos',
                'unique_together': {('group', 'modulo')},
            },
        ),
        migrations.CreateModel(
            name='PermisoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(default=True)),
                ('puede_usar', models.BooleanField(default=True)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='client.elemento')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_elementos', to='auth.group')),
            ],
            options={
                'verbose_name': 'Permiso de Elemento',
                'verbose_name_plural': 'Permisos de Elementos',
                'unique_together': {('group', 'elemento')},
            },
        ),
        migrations.CreateModel(
            name='PermisoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(default=False)),
                ('puede_usar', models.BooleanField(default=False)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='client.componente')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_granulares', to='auth.group')),
            ],
            options={
                'verbose_name': 'Permiso de Grupo',
                'verbose_name_plural': 'Permisos de Grupos',
                'unique_together': {('group', 'componente')},
            },
        ),
    ]
