# Generated by Django 5.1.7 on 2026-03-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='tipo_evento',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('modulo', 'Acceso a módulo'), ('elemento', 'Interacción con elemento'), ('crear', 'Creación de dato'), ('editar', 'Edición de dato'), ('eliminar', 'Eliminación de dato'), ('buscar', 'Búsqueda / Consulta'), ('acceso_denegado', 'Acceso denegado (403)')], max_length=20),
        ),
    ]
